image_folder: ../../data/neurons_skeletons/
masurements_csv_file: ../../results/neuron_measurements.csv

skeleton_images:
  - image: 
    filename: MAX_LG14.CNG.tif
    start_position:
      - position:
          x: 56
          y: 227
  
  - image: 
    filename: MAX_LG8.CNG.tif
    start_position:
      - position:
          x: 259
          y: 352
  
  - image: 
    filename: MAX_HG5.CNG.tif
    start_position: 
      - position:
          x: 372
          y: 380
  
  - image: 
    filename: MAX_HG12.CNG.tif
    start_position:
      - position:
          x: 131
          y: 102

  - image: 
    filename: MAX_sc147_e2216_26.CNG.tif
    start_position:
      - position:
          x: 762
          y: 341

  - image: 
    filename: A6_001_S.tif
    start_position:
      - position:
          x: 573
          y: 2483

  - image: 
    filename: A6_002_S.tif
    start_position:
      - position:
          x: 299
          y: 398

  - image: 
    filename: A6_009_S.tif
    start_position:
      - position:
          x: 448
          y: 391