image_folder: /Users/zianfanti/Trabajo/tree_representation/data/neuro_morpho/neurons_skeletons/

skeleton_images:
  - image: 
    filename: MAX_LG14.CNG.tif
    start_position:
      - position:
          x: 56
          y: 227
  
  - image: 
    filename: MAX_LG8.CNG.tif
    start_position:
      - position:
          x: 259
          y: 352
  
  - image: 
    filename: MAX_HG5.CNG.tif
    start_position: 
      - position:
          x: 117
          y: 242
  
  - image: 
    filename: MAX_HG12.CNG.tif
    start_position:
      - position:
          x: 131
          y: 102

  - image: 
    filename: MAX_sc147_e2216_26.CNG.tif
    start_position:
      - position:
          x: 762
          y: 341